task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 1
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /raid/colon_reproduce/real-colon-dataset/real_colon_dataset_coco_fmt_3subsets_poslesion1000_negratio0/train_images
    ann_file: /raid/colon_reproduce/real-colon-dataset/real_colon_dataset_coco_fmt_3subsets_poslesion1000_negratio0/train_ann.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 16
  drop_last: True 
  collate_fn:
    type: BatchImageCollateFuncion


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /raid/colon_reproduce/real-colon-dataset/real_colon_dataset_coco_fmt_3subsets_poslesion1000_negratio0/validation_images
    ann_file: /raid/colon_reproduce/real-colon-dataset/real_colon_dataset_coco_fmt_3subsets_poslesion1000_negratio0/validation_ann.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~ 
  shuffle: False
  num_workers: 16
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion
