__include__: [
  '/colon_workspace/RT-DETR/rtdetrv2_pytorch/configs/dataset/colon_detection.yml',
  '/colon_workspace/RT-DETR/rtdetrv2_pytorch/configs/runtime.yml',
  '/colon_workspace/RT-DETR/rtdetrv2_pytorch/configs/rtdetrv2/include/dataloader.yml',
  '/colon_workspace/RT-DETR/rtdetrv2_pytorch/configs/rtdetrv2/include/optimizer.yml',
  '/colon_workspace/RT-DETR/rtdetrv2_pytorch/configs/rtdetrv2/include/rtdetrv2_r50vd.yml',
]


output_dir: ./output/log_640_rtdetrv2_timm_r50vd_6x_colon_20_epoch_finetune_pos_backbone_pos1_neg1

RTDETR: 
  backbone: TimmModel
  encoder: HybridEncoder
  decoder: RTDETRTransformerv2

TimmModel:
  name: resnet50
  return_layers: ['layer2', 'layer3', 'layer4']
  pretrained_path: /colon_workspace/resnet_50_a3_pretrained.pth.tar
  pretrained: False
  freeze_at: -1
  freeze_norm: False

HybridEncoder:
  in_channels: [512, 1024, 2048]
  feat_strides: [8, 16, 32]

  # intra
  hidden_dim: 256
  use_encoder_idx: [2]
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.
  enc_act: 'gelu'
  
  # cross
  expansion: 1.0
  depth_mult: 1
  act: 'silu'


RTDETRTransformerv2:
  num_classes: 1
  feat_channels: [256, 256, 256]
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  num_levels: 3
  aux_loss: True

  num_layers: 6
  num_queries: 300

  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 1.0 # 1.0 0.4

  eval_idx: -1

  # NEW
  num_points: [4, 4, 4] # [3,3,3] [2,2,2]
  cross_attn_method: default # default, discrete
  query_select_method: default # default, agnostic 


RTDETRPostProcessor:
  num_top_queries: 300
  num_classes: 1


optimizer:
  type: AdamW
  params: 
    # - 
    #   params: '^(?=.*backbone)(?!.*norm).*$'
    #   lr: 0.0001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0003
  betas: [0.9, 0.999]
  weight_decay: 0.0001
